Home task webpack
LxndrKrchvtsv/ReactJsMentor2022Q2 pull request #1
Opened 2022-05-17 09:49 UTC by LxndrKrchvtsv

This PL contains 1 and 2 tasks.

2022-05-18 22:37 UTC, Dmitry-White requested changes
Nice work!
Left a couple of comments for further improvements

2022-06-06 19:29 UTC, Dmitry-White approved these changes
Great job!
Approving upfront, though left some comments/suggestions

2022-06-06 19:29 UTC, Dmitry-White commented on .prettierrc
> +  "tabWidth": 4,
Sure you want to have so much indentation going forward? :)
React JSX tends to get pretty nested :)

2022-06-07 08:53 UTC, LxndrKrchvtsv commented on .prettierrc
> +  "tabWidth": 4,
@Dmitry-White I think, yes, because it's just more comfortable to me.) I don't like tags with width 2 spaces.)

2022-06-07 09:07 UTC, merged