Component part 1 has been completed
LxndrKrchvtsv/ReactJsMentor2022Q2 pull request #2
Opened 2022-07-15 16:31 UTC by LxndrKrchvtsv

2022-07-20 19:35 UTC, Dmitry-White requested changes
Looks solid, let's work on some additional improvements then!

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/AddMovie/AddMovie.tsx
> +	return <Button classButton={Styles.add__movie__button} label={'+ ADD MOVIE'} />;
Consider creating a separate Icon component and use it here instead of manual string character "+".
This Icon component might be implemented in a reusable way containing conditional logic to change the displayed icon depending on a prop.

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +					<p>{'Seems like an error occured!'}</p>
Consider adding more flexibility and value to your ErrorBoundry component by making it accept a specific error message from its props.

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/GenreToggle/GenreToggle.tsx
> +type StateGenreToggle = {
Seeing how many types you define, it would make sense to split React and TypeScript into separate files.
Consider creating separate files named something like `interfaces.ts` or `types.ts` for the sake of readability and consistency - this way you'd always know that everything TS-related in any folder is kept in the file named `interfaces.ts` or `types.ts`.

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/MoviesList/MovieItem/MovieItem.tsx
> +				<div className={Styles.movie__date__release}>{releaseDate.slice(0, 4)}</div>
Consider extracting date slicing  to the root level "src/utils" folder for the same of potential reuse.

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/MoviesList/MoviesList.tsx
> +			{moviesList?.map((movie) => {
Consider extracting any JS logic from JSX into separate functions, placed either insider of the component body or outside (depends on scoping rules that apply to these functions).
Ideally, in the case of arrays, you'd have:
1. `const renderItem = (item) => ... som JSX ....;`
2. `const renderList = (list) => list.map(renderItem);`

2022-07-20 19:35 UTC, Dmitry-White commented on src/api/api.ts
> +const baseUrl = 'http://localhost:4000/';
Consider creating a "constants" folder under "src/core" where all the main reusable non-react things will be stored.

In this particular case you'll also need to move your "src/api" under "src/core/api".

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/AddMovie/AddMovie.tsx
> +	return <Button classButton={Styles.add__movie__button} label={'+ ADD MOVIE'} />;
I can see that you're using a lot of raw user-facing strings which is not extendable and error-prone.
Under "src/core" folder that you create after one of the above comments consider creating a folder "i18y" which stands for "internationalization". This folder in real project usually holds translation object in cases when they're stored in the source code. The folder structure consists of "index.js/ts" file and a number of "*.js/ts" files for different languages (e.g. "en.js" for English or "ge.js" for German). Each of these language files contains an object with the same keys but different values for the target language. The idea behind it is to decouple the selected language for a website and the actual text used in all the components.

E.g. your "Button" will have a label text in the JSX as follows:
label={I18Y['EN'].ADD_MOVIE} for English and label={I18Y['GE'].ADD_MOVIE} for German. As you might guess, this would allow to hook up language selection logic from your app that will pass either "EN" or "GE" to the I18Y object, but you the same "ADD_MOVIE" key - and end up with different language texts displayed on the live website.

In the end, your task is to create such object (could be only English for now) and go though the whole app and change the hard-coded text to the usage of this I18Y object.

2022-07-20 19:35 UTC, Dmitry-White commented on src/components/AddMovie/AddMovie.tsx
> +	return <Button classButton={Styles.add__movie__button} label={'+ ADD MOVIE'} />;
It would also make sense to extend the Button component logic to have `beforeIcon` and `afterIcon` props that render conditionally around `label` prop content.

2022-08-04 08:14 UTC, LxndrKrchvtsv commented on src/components/AddMovie/AddMovie.tsx
> +	return <Button classButton={Styles.add__movie__button} label={'+ ADD MOVIE'} />;
Thank you, @Dmitry-White!  It's pretty useful advice! I'll implement it after finished all Hometasks.

2022-08-04 14:14 UTC, merged